// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvuwj2MolQ-5SdGvJAR9Hez3tfFjwPQh0',
    appId: '1:825681413946:web:4566d8696582d43dc67203',
    messagingSenderId: '825681413946',
    projectId: 'to-do-list-app-6869c',
    authDomain: 'to-do-list-app-6869c.firebaseapp.com',
    storageBucket: 'to-do-list-app-6869c.appspot.com',
    measurementId: 'G-MBXXFXH4JW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEm-wj6W_Qd86lIDtH77VekYZZ_79JDr0',
    appId: '1:825681413946:android:f2ab6ac7eecad62ec67203',
    messagingSenderId: '825681413946',
    projectId: 'to-do-list-app-6869c',
    storageBucket: 'to-do-list-app-6869c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZjW3i9rbliqkz6LxVjjUUYh0rqsjeTMY',
    appId: '1:825681413946:ios:a31136b235109bc8c67203',
    messagingSenderId: '825681413946',
    projectId: 'to-do-list-app-6869c',
    storageBucket: 'to-do-list-app-6869c.appspot.com',
    iosClientId:
        '825681413946-m7om9rihefgc4tmcc7ktv1gskgjj1v5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterToDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZjW3i9rbliqkz6LxVjjUUYh0rqsjeTMY',
    appId: '1:825681413946:ios:91981236e8aa0a2fc67203',
    messagingSenderId: '825681413946',
    projectId: 'to-do-list-app-6869c',
    storageBucket: 'to-do-list-app-6869c.appspot.com',
    iosClientId:
        '825681413946-f84kkd90dhe5ps3t1i63eo7cvmb9kbod.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterToDoList.RunnerTests',
  );
}
